spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-5t7sas8q.sql.tencentcdb.com:24769/oj?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: own
    password: upcJavaee.com

    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8000


mybatis:
  mapper-locations: classpath:mapper/*.xml