spring:
  datasource:
    url: jdbc:mysql://42.192.123.219:3306/oj?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Mixed2022.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8000


mybatis:
  mapper-locations: classpath:mapper/*.xml